version: '3'

services:

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '${NGINX_PORT:-8080}:80'
    volumes:
      - '../guestbook:/var/www/html'
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database

  php:
    container_name: php
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - '../guestbook:/var/www/html'
    ports:
      - '${PHP_PORT:-9000}:9000'
    depends_on:
      - database

  database:
    container_name: database
    image: postgres:${POSTGRES_VERSION:-13}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_USER: ${POSTGRES_USER:-symfony}
    ports:
      - '${POSTGRES_PORT:-5432}:5432'
    volumes:
      - 'db-data:/var/lib/postgresql/data:rw'

volumes:
  db-data: